version: '3.8'

services:
  # Payments Service
  payment-mcp:
    build:
      context: ./payment-mcp
    container_name: payment-mcp
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_BackendAPIs__TransactionsApiUrl=http://transactions-api:5002
    networks:
      - business-tools-network

  # Transactions Service  
  transactions-api:
    build:
      context: ./transactions-api
    container_name: transactions-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - business-tools-network

  # Additional Service (generic placeholder)
  account-mcp:
    build:
      context: ./account-mcp
    container_name: account-mcp
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - business-tools-network

# Network configuration
networks:
  business-tools-network:
    driver: bridge

# Optional volume for persistent data
volumes:
  business-data:
    driver: local