openapi: 3.0.3
info:
  title: API de Cuentas
  version: 1.0.0
paths:
  /users/{user_name}/accounts:
    get:
      summary: Obtener la lista de cuentas de un usuario específico
      description: Obtener la lista de cuentas de un usuario específico
      operationId: getAccountsByUserName
      parameters:
        - name: user_name
          description: Nombre de usuario una vez autenticado.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de cuentas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /accounts/{accountid}:
    get:
      summary: Obtener detalles de la cuenta y métodos de pago disponibles
      description: Obtener detalles de la cuenta y métodos de pago disponibles
      operationId: getAccountDetails
      parameters:
        - name: accountid
          description: Identificador de la cuenta.
          in: path
          required: true
          schema:
            type: integer
            example: 123456
      responses:
        '200':
          description: Detalles de la cuenta
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Account'
  /accounts/{accountid}/paymentmethods/{methodid}:
    get:
      summary: Obtener detalle del método de pago con saldo disponible
      description: Obtener detalle del método de pago con saldo disponible
      operationId: getPaymentMethodDetails
      parameters:
        - name: accountid
          description: Identificador de la cuenta.
          in: path
          required: true
          schema:
            type: integer
            example: 123456
        - name: methodid
          description: Identificador del método de pago disponible para la cuenta.
          in: path
          required: true
          schema:
            type: integer
            example: 74839113
      responses:
        '200':
          description: Detalles del método de pago
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/PaymentMethod'
  /accounts/{accountid}/registeredBeneficiaries:
    get:
      summary: Obtener la lista de beneficiarios registrados para una cuenta específica
      description: Obtener la lista de beneficiarios registrados para una cuenta específica
      operationId: getBeneficiaryMethodDetails
      parameters:
        - name: accountid
          description: Identificador de la cuenta.
          in: path
          required: true
          schema:
            type: integer
            example: 123456
      responses:
        '200':
          description: Beneficiarios registrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Beneficiary'
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          description: Identificador único de la cuenta
        userName:
          type: string
          description: Identificador único del usuario
        accountHolderFullName:
          type: string
          description: Nombre completo del titular de la cuenta
        currency:
          type: string
          description: Moneda de la cuenta
        activationDate:
          type: string
          description: Fecha en que se activó la cuenta
        balance:
          type: string
          description: Saldo actual de la cuenta
        paymentMethods:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMethod'
          description: Lista de métodos de pago asociados a la cuenta
    PaymentMethodSummary:
      type: object
      properties:
        id:
          type: string
          description: Identificador único del método de pago
        type:
          type: string
          description: Tipo de método de pago
        activationDate:
          type: string
          description: Fecha en que se activó el método de pago
        expirationDate:
          type: string
          description: Fecha de expiración del método de pago
    PaymentMethod:
      type: object
      properties:
        id:
          type: string
          description: Identificador único del método de pago
        type:
          type: string
          description: Tipo de método de pago
        activationDate:
          type: string
          description: Fecha en que se activó el método de pago
        expirationDate:
          type: string
          description: Fecha de expiración del método de pago
        availableBalance:
          type: string
          description: Saldo disponible del método de pago
        cardNumber:
          type: string
          description: Número de tarjeta del método de pago
    Beneficiary:
      type: object
      properties:
        id:
          type: string
          description: Identificador único del beneficiario
        fullName:
          type: string
          description: Nombre completo del beneficiario
        bankCode:
          type: string
          description: Código bancario del banco del beneficiario
        bankName:
          type: string
          description: Nombre del banco del beneficiario
