openapi: 3.0.3
info:
  title: API de Pagos
  version: 1.0.0
paths:
  /payments:
    post:
      operationId: submitPayment
      summary: Enviar una solicitud de pago
      description: Enviar una solicitud de pago
      requestBody:
        required: true
        description: Pago a enviar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: Solicitud de pago enviada correctamente
        '400':
          description: Cuerpo de la solicitud inválido
        '500':
          description: Error interno del servidor
components:
  schemas:
    Payment:
      type: object
      properties:
        description:
          type: string
          description: Descripción del pago
        recipientName:
          type: string
          description: Nombre del beneficiario
        recipientBankCode:
          type: string
          description: Código bancario del beneficiario
        accountId:
          type: string
          description: Identificador de la cuenta
        paymentMethodId:
          type: string
          description: Identificador del método de pago
        paymentType:
          type: string
          description: 'Tipo de pago: tarjeta de crédito, transferencia bancaria, débito directo, visa, mastercard, paypal, etc.'
        amount:
          type: string
          description: Monto del pago
        timestamp:
          type: string
          description: Marca de tiempo del pago
  requestBodies:
    Payment:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Payment'
      description: Objeto de pago a enviar
