openapi: 3.0.3
info:
  title: API de Historial y Reportes de Transacciones
  version: 1.0.0
paths:
  /transactions/{accountid}:
    get:
      summary: Obtener lista de transacciones.
      description: Obtiene la lista de transacciones, con opción a filtrar por nombre del beneficiario
      operationId: getTransactionsByRecipientName
      parameters:
        - name: accountid
          description: Identificador de la cuenta.
          in: path
          required: true
          schema:
            type: integer
            example: 123456
        - name: recipient_name
          description: Nombre del beneficiario
          in: query
          required: false
          schema:
            type: string
            example: contoso

      responses:
        '200':
          description: Lista de transacciones para un beneficiario específico
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
    post:
      operationId: notifyTransaction
      summary: Notificar una transacción bancaria para almacenarla en el historial
      description: Notificar una transacción bancaria para almacenarla en el historial
      parameters:
        - name: accountid
          description: Identificador de la cuenta.
          in: path
          required: true
          schema:
            type: integer
            example: 123456
      requestBody:
        required: true
        description: Transacción a notificar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transacción registrada exitosamente
        '400':
          description: Cuerpo de la solicitud inválido
        '500':
          description: Error interno del servidor
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: Identificador único de la transacción
        description:
          type: string
          description: Descripción de la transacción con el motivo del pago y otros detalles
        type:
          type: string
          description: Tipo de transacción expresado como ingreso o egreso
        recipientName:
          type: string
          description: Nombre del beneficiario
        recipientBankReference:
          type: string
          description: Referencia bancaria del beneficiario
        accountId:
          type: string
          description: Identificador de la cuenta asociada a la transacción
        paymentType:
          type: string
          description: 'Tipo de pago: tarjeta de crédito, transferencia bancaria, débito directo, visa, mastercard, paypal, etc.'
        amount:
          type: string
          description: Monto de la transacción
        timestamp:
          type: string
          format: date-time
          description: Marca de tiempo de la transacción
